name: R code
description: Ask a question about R code.
labels: question
body:
  - type: textarea
    id: description
    attributes:
      label: Description of the question
      description: A clear and concise description of what the main question is.
    validations:
      required: true
  
  - type: textarea
    id: repex
    attributes:
      label: Minimal example
      description: A code snippet that you have tried and have questions about
      render: R
      placeholder: |
        library(ktplots)

        do_something_that_you_are_wondering_about(data)

  - type: textarea
    id: stacktrace
    attributes:
      label: Any error message produced by the code above
      description: Please paste the entire error message if any
      render: R
      placeholder: |
        Error in class(scdata) %in% c("SingleCellExperiment", "SummarizedExperiment") : 
          argument "scdata" is missing, with no default
   
  - type: textarea
    id: os
    attributes:
      label: OS information
      placeholder: |
        e.g. MacOS

  - type: textarea
    id: versions
    attributes:
      label: sessioninfo
      description: Please paste everything from `sessionInfo()`
      placeholder: |
        R version 4.1.3 (2022-03-10)
        Platform: x86_64-apple-darwin17.0 (64-bit)
        Running under: macOS Catalina 10.15.7
        
        Matrix products: default
        BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
        LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
        
        locale:
        [1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
        
        attached base packages:
        [1] stats     graphics  grDevices utils     datasets  methods   base     
        
        other attached packages:
        [1] ktplots_1.1.20 ggplot2_3.3.5 
        
        loaded via a namespace (and not attached):
        [1] ggrepel_0.9.1       Rcpp_1.0.8.3        circlize_0.4.14     lattice_0.20-45     tidyr_1.2.0        
        [6] prettyunits_1.1.1   ps_1.6.0            gtools_3.9.2        assertthat_0.2.1    rprojroot_2.0.3    
        [11] digest_0.6.29       utf8_1.2.2          ggforce_0.3.3       plyr_1.8.7          R6_2.5.1           
        [16] pillar_1.7.0        GlobalOptions_0.1.2 rlang_1.0.2         callr_3.7.0         Matrix_1.4-0       
        [21] desc_1.4.1          devtools_2.4.3      stringr_1.4.0       igraph_1.3.0        polyclip_1.10-0    
        [26] munsell_0.5.0       compiler_4.1.3      pkgconfig_2.0.3     pkgbuild_1.3.1      shape_1.4.6        
        [31] tidyselect_1.1.2    tibble_3.1.6        gridExtra_2.3       graphlayouts_0.8.0  fansi_1.0.3        
        [36] viridisLite_0.4.0   crayon_1.5.1        dplyr_1.0.8         withr_2.5.0         MASS_7.3-55        
        [41] brio_1.1.3          grid_4.1.3          gtable_0.3.0        lifecycle_1.0.1     DBI_1.1.2          
        [46] magrittr_2.0.3      scales_1.1.1        stringi_1.7.6       cli_3.2.0           cachem_1.0.6       
        [51] reshape2_1.4.4      farver_2.1.0        viridis_0.6.2       fs_1.5.2            remotes_2.4.2      
        [56] testthat_3.1.3      ellipsis_0.3.2      generics_0.1.2      vctrs_0.4.0         RColorBrewer_1.1-3 
        [61] tools_4.1.3         glue_1.6.2          tweenr_1.0.2        purrr_0.3.4         ggraph_2.0.5       
        [66] processx_3.5.3      pkgload_1.2.4       fastmap_1.1.0       colorspace_2.0-3    sessioninfo_1.2.2  
        [71] tidygraph_1.2.0     memoise_2.0.1       usethis_2.1.5
  
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: |
        Add any other context about the problem here.
